Traceback (most recent call last):
  File "main.py", line 75, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/88/7/117159/Desktop/BCI_MI_Classification/train_function.py", line 52, in train_model
    out = model(temp_data)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/88/7/117159/Desktop/BCI_MI_Classification/models.py", line 94, in forward
    X_data = self.batchnorm_4(X_data)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/zhome/88/7/117159/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.91 GiB (GPU 0; 31.75 GiB total capacity; 23.13 GiB already allocated; 1.22 GiB free; 23.90 GiB reserved in total by PyTorch)
