Traceback (most recent call last):
  File "main.py", line 61, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/train_function.py", line 45, in train_model
    out = model(temp_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/models.py", line 80, in forward
    X_data = self.layer_img1(X_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 13.02 GiB already allocated; 8.50 MiB free; 14.23 GiB reserved in total by PyTorch)
