Traceback (most recent call last):
  File "main.py", line 70, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/train_function.py", line 45, in train_model
    out = model(temp_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/models.py", line 80, in forward
    X_data = self.layer_img1(X_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1136, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 29.52 GiB already allocated; 9.50 MiB free; 30.51 GiB reserved in total by PyTorch)
